language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - mkdir -p build/logs/
  - phpunit --coverage-clover build/logs/coverage.xml --configuration phpunit.xml.dist

